sudo: required 
services: 
  - docker 
branches: 
  only: 
    - complex
before_install: 
  - docker build -t CI=true jsmile65/multi-docker -f ./client/Dockerfile.dev 
script: 
  - docker run jsmile65/multi-docker npm test -- --coverage
after_success: 
  - docker build jsmile65/multi-client ./client 
  - docker build jsmile65/multi-nginx ./nginx 
  - docker build jsmile65/multi-server ./server 
  - docker build jsmile65/multi-worker ./worker 
  # Login docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # Take those images and push them to docker hub
  - docker push jsmile65/multi-client 
  - docker push jsmile65/multi-nginx 
  - docker push jsmile65/multi-server 
  - docker push jsmile65/multi-worker 

