sudo: required 
services: 
  - docker 
before_install: 
  - docker build -t jsmile/multi-docker -f ./client/Dockerfile.dev ./client 
script: 
  - docker run -e CI=true jsmile/multi-docker npm test -- --coverage
after_success: 
  - docker build -t jsmile/multi-client ./client 
  - docker build -t jsmile/multi-nginx ./nginx 
  - docker build -t jsmile/multi-server ./server 
  - docker build -t jsmile/multi-worker ./worker 
  # Login docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  # Take those images and push them to docker hub
  - docker push jsmile/multi-client 
  - docker push jsmile/multi-nginx 
  - docker push jsmile/multi-server 
  - docker push jsmile/multi-worker 
